### PR TITLE
Alignment change in the ssh command user interface

### PR DESCRIPTION
**Pull request by shtukas**

### CODE REVIEW

**Comment by shtukas** [comment]
Before:

screen shot 2018-01-25 at 14 24 36

**Comment by shtukas** [comment]
After:

screen shot 2018-01-25 at 14 27 29

**Comment by adamnfish** [comment]
I think the leading space was there on purpose? A leading space prevents the command from going into your bash history. In this case it's a temporary one-shot command so there's no reason you'd want it to be present after you've run it.

Note: this is also what Janus does to prevent pasted credentials from showing up.

**Comment by shtukas** [comment]
Point taken. I have (re) discovered something today. Closing

**Comment by aug24** [comment]
+1

**Pull request closed without merging**
